---

- hosts: localhost
  connection: local
  become: yes
  become_user: "{{ user }}"
  vars_files:
    - vars/common.yml

  roles:
    - role: common
      tags: common
    - role: python
      tags: python
    - role: node
      tags: node
    - role: docker
      tags: docker
    - role: dotfiles
      tags: dotfiles
    - role: emacs
      tags: emacs
    - role: latex
      tags: latex
    - role: wine
      tags: wine
