#!/bin/bash

### Pretty path
function path(){
    tr ':' '\n' <<< "$PATH" | sed -e 's|'$HOME'|'$orange'~'$reset'|'
}

# Simple calculator
calc() {
    local result=""
    result="$(printf "scale=10;%s\\n" "$*" | bc --mathlib | tr -d '\\\n')"
    #           └─ default (when `--mathlib` is used) is 20

    if [[ "$result" == *.* ]]; then
        # improve the output for decimal numbers
        # add "0" for cases like ".5"
        # add "0" for cases like "-.5"
        # remove trailing zeros
        printf "%s" "$result" |
            sed -e 's/^\./0./'  \
                -e 's/^-\./-0./' \
                -e 's/0*$//;s/\.$//'
    else
        printf "%s" "$result"
    fi
    printf "\\n"
}

# Create a new directory and enter it
mkd() {
    mkdir -p "$@"
    cd "$@" || exit
}

# Start an HTTP server from a directory, optionally specifying the port
server() {
    local port="${1:-8000}"
    busybox httpd -f -p "$port"
}

# Syntax-highlight JSON strings or files
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
json() {
    if [ -t 0 ]; then # argument
        python -mjson.tool <<< "$*" | pygmentize -l javascript
    else # pipe
        python -mjson.tool | pygmentize -l javascript
    fi
}

yaml() {
    if [ -t 0 ]; then # argument
        python -c 'import yaml,sys;s=sys.stdin.read();yaml.safe_load(s);print(s)' <<< "$*" | pygmentize -l YAML
    else # pipe
        python -c 'import yaml,sys;s=sys.stdin.read();yaml.safe_load(s);print(s)' | pygmentize -l YAML
    fi
}

yaml2json() {
    if [ -t 0 ]; then # argument
        python -c 'import yaml,sys,json;print(json.dumps(yaml.safe_load(sys.stdin.read())))' <<< "$*" |json
    else # pipe
        python -c 'import yaml,sys,json;print(json.dumps(yaml.safe_load(sys.stdin.read())))' |json
    fi
}

# Show all the names (CNs and SANs) listed in the SSL certificate
# for a given domain
getcertnames() {
    if [ -z "${1}" ]; then
        echo "ERROR: No domain specified."
        return 1
    fi

    local domain="${1}"
    echo "Testing ${domain}…"
    echo ""; # newline

    local tmp
    tmp=$(echo -e "GET / HTTP/1.0\\nEOT" \
              | openssl s_client -connect "${domain}:443" 2>&1)

    if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
        local certText
        certText=$(echo "${tmp}" \
                       | openssl x509 -text -certopt "no_header, no_serial, no_version, \
      no_signame, no_validity, no_issuer, no_pubkey, no_sigdump, no_aux")
        echo "Common Name:"
        echo ""; # newline
        echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//"
        echo ""; # newline
        echo "Subject Alternative Name(s):"
        echo ""; # newline
        echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
            | sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\\n" | tail -n +2
        return 0
    else
        echo "ERROR: Certificate not found."
        return 1
    fi
}

# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` directory, listing directories first. The output gets piped into
# `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
tre() {
    tree -aC -I "$TREE_IGNORE" --dirsfirst "$@" | less -FRX
}

# Runs "eval $(docker-machine env $1)" in a subshell
dockerenv() {
    bash --init-file <(echo " . \"$HOME/.bashrc\"; eval $(docker-machine env ${1})")
}
