#!/bin/bash

function add_path_exists() {
    for p in "$@"
    do
        if [ -d "$p" ]; then
            export PATH="$p:$PATH"
        fi
    done
}

# set PATH so it includes user's private bin if it exists
add_path_exists "$HOME/.local/bin" "$HOME/bin"

# Cabal
add_path_exists "$HOME/.cabal/bin"

# Yarn
add_path_exists "$HOME/.yarn/bin"

## Android sdk
add_path_exists "$HOME/android-sdk/platform-tools" "$HOME/android-sdk/tools"

### Yarn
add_path_exists "$HOME/.yarn/bin"
