---
- name: Add yarn repo public key
  apt_key:
    id: 1646B01B86E50310 # this could change in the future
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  become_user: root

- name: Add yarn's repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn
    update_cache: true
  become_user: root

- name: Install yarn
  apt:
    name: yarn
    install_recommends: no
    state: latest
  become_user: root

- name: Install nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_root }}"
    update: no

- name: Install node
  shell: "NVM_DIR={{ nvm_root }} . {{nvm_exec}} && nvm install {{node_version}} && nvm alias default {{node_version}}"

- set_fact:
    node_packages:
      - tern
      # This corresponds to lerna version 3 (currently in beta)
      - lerna@next
      - nodemon
      - svgo

- name: Install global packages
  shell: |
    NVM_DIR={{ nvm_root }} . {{nvm_exec}} \
    && yarn global add {{ node_packages | join(' ')}}
    
