---
- name: Install updates
  apt:
    cache_valid_time: 600
    upgrade: dist
  become_user: root

- root: Gather os specific variables
  include_vars: "{{ ansible_distribution | lower}}.yml"

- set_fact:
    security_pkgs:
      - ca-certificates
      - ufw
    apt_pkgs:
      - apt-transport-https
      - software-properties-common
      - synaptic
      - gnupg2
      - snapd
    build_pkgs:
      - build-essential
      - libssl-dev
    system_pkgs:
      - lm-sensors
    cli_pkgs:
      - graphviz
      - htop
      - tree
      - xinput
      - net-tools
      - unzip
      - unrar
      - bash-completion
      - git
      - wget
      - curl
    app_pkgs:
      - wireshark

- name: Install software from repositories
  apt:
    name: "{{security_pkgs}} + {{apt_pkgs}} + {{build_pkgs}} + {{system_pkgs}} + \
    {{cli_pkgs}} + {{distro_packages}}"
    state: latest
  become_user: root

- name: Get list of installed snaps
  shell: snap list | tail -n +2 | awk '{ print $1}'
  register: snap_installed
  changed_when: false

- name: Install software from snap
  command: snap install {{item}}
  become_user: root
  when: item not in snap_installed.stdout_lines
  with_items:
    - vlc
    - inkscape
    - obs-studio
    - spotify
