#!/usr/bin/env bash

# append to the history file, don't overwrite it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell


for file in ~/dotfiles/dispatch/{default,functions,prompt,aliases,dockerfunc,extra}; do
	  if [[ -r "$file" ]] && [[ -f "$file" ]]; then
		    # shellcheck source=/dev/null
		    source "$file"
	  fi
done
unset file

# Load nvm without calling "nvm use"
if [ -s "$NVM_DIR/nvm.sh" ]; then
    source "$NVM_DIR/nvm.sh" --no-use
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi
