#!/usr/bin/env bash
echo "Dispatch: once"
source "${HOME}/dotfiles/exports"
source "${HOME}/dotfiles/path"
source "${HOME}/dotfiles/aliases"
echo "Sourced"

# load nvm
if [ -s "$NVM_DIR/nvm.sh" ]; then
    source "$NVM_DIR/nvm.sh"
fi

# disable touchpad by default
touchpad-off
