#!/usr/bin/env bash

source "${HOME}/dotfiles/path"
source "${HOME}/dotfiles/exports"
source "${HOME}/dotfiles/aliases"

# load nvm
if [ -s "$NVM_DIR/nvm.sh" ]; then
    source "$NVM_DIR/nvm.sh"
fi

# disable touchpad by default
touchpad-off
