#!/usr/bin/env bash
. "${HOME}/dotfiles/exports"
. "${HOME}/dotfiles/path"
. "${HOME}/dotfiles/aliases"

# load nvm
if [ -s "$NVM_DIR/nvm.sh" ]; then
    . "$NVM_DIR/nvm.sh"
fi

# disable touchpad by default
touchpad-off
