#!/bin/bash

is_in_path() {
    case ":$PATH:" in
        *":$@:"* ) return 0;;
        *) return 1;;
    esac
}

add_path_exists() {
    for p in "$@"; do
        if [ -d "$p" ] && ! is_in_path "$p"; then
            PATH="$p:$PATH";
        fi
    done
}

# Adds a directory to the end of the path
add_to_end_path_exists() {
    for p in "$@"; do
        if [ -d "$p" ] && ! is_in_path "$p"; then
            PATH="$PATH:$p";
        fi
    done
}

add_path_for_command() {
    if command -v "$1" > /dev/null 2>&1; then
        shift
        for p in "$@"; do
            add_path_exists $p
        done
    fi
}

# In debian, /sbin is not added to the path by default
add_to_end_path_exists /sbin

# Cabal
add_path_for_command cabal "$HOME/.cabal/bin"

## Android sdk
add_path_exists "$ANDROID_HOME/platform-tools" \
                "$ANDROID_HOME/tools/bin"

# Pyenv
add_path_exists "${PYENV_ROOT}/bin" "${PYENV_ROOT}/shims"

# Yarn
add_path_for_command yarn "$HOME/.yarn/bin"

# set PATH so it includes user's private bin if it exists
add_path_exists "$HOME/bin"

