---

python_3_version: 3.6.5
python_2_version: 2.7.15

pyenv_root: "{{ ansible_env.HOME }}/.pyenv"
pyenv_owner: "{{ ansible_env.USER }}"
pyenv_exec: "{{ pyenv_root }}/bin/pyenv"

python_build_dependencies:
  - make
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - llvm
  - libncurses5-dev
  - xz-utils
  - tk-dev
