---
- name: Check emacs is present
  shell: command -v emacs >/dev/null 2>&1
  register: check_emacs
  ignore_errors: yes

- when: check_emacs.rc
  block:
    - name: Install build dependencies
      apt:
        name: emacs25
        state: build-dep
        cache_valid_time: 600
      become_user: root
      when:

    - name: Install gnutls-dev
      apt:
        name: gnutls-dev
        state: latest
      become_user: root

    - name: Download emacs source
      unarchive:
        src: http://ftp.gnu.org/gnu/emacs/emacs-{{ emacs_version }}.tar.gz
        dest: "{{ emacs_source_path }}"
        remote_src: yes

    - name: Configure emacs source
      command:
        chdir: "{{ emacs_source_path }}"
        command: "{{ emacs_source_path }}/configure"

    - name: Build sources
      make:
        chdir: "{{ emacs_source_path }}"

    - name: Install binaries
      make:
        chdir: "{{ emacs_source_path }}"
        target: install
      become_user: root

- name: Ensure spacemacs is cloned
  git:
    repo: https://github.com/syl20bnr/spacemacs.git
    dest: "{{ ansible_user_dir }}/.emacs.d"
    clone: yes
    version: develop
    update: no

- name: Create Fira Mono font directory
  file:
    path: "{{ ansible_env.HOME }}/.fonts/FiraMono"
    state: directory
    mode: 0755

- name: Check if fira Mono is installed
  stat:
    path: "{{ ansible_env.HOME }}/.fonts/FiraMono/FiraMono-Regular.ttf"
  register: fira_mono_stat_res

- name: Install Fira Mono
  when: fira_mono_stat_res.stat.exists == false
  block:
    - get_url:
        url: https://fonts.google.com/download?family=Fira%20Mono
        dest: /tmp/FiraMono.zip

    - unarchive:
        dest: "{{ ansible_env.HOME }}/.fonts/FiraMono"
        src: /tmp/FiraMono.zip
        remote_src: yes

- name: Install Quivira font
  get_url:
    url: http://www.quivira-font.com/files/Quivira.otf
    dest: "{{ ansible_env.HOME }}/.fonts/Quivira.otf"

- name: Install Symbola and noto fonts
  apt:
    name:
      - fonts-symbola
      - fonts-noto
    state: latest
  become_user: root

- name: Remove unifont package
  apt:
    name: unifont
    state: absent
  become_user: root
